version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/danielberndt.net

    steps:
      - checkout
      - type: cache-restore
        name: Restore yarn cache
        key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - type: cache-save
        name: Store yarn cache
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
      - run: yarn lint
      - run: yarn is-prettier
      - run: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build
